export enum Actions {
    UPDATE_COD_PROV,
    UPDATE_COD_TOWN,
    UPDATE_DATA,
    TOGGLE_GEOLOCATION,
    UPDATE_DATA_TO_SHARE,
    UPDATE_FILTERED_TOWNS,
    UPDATE_ORDER_VALUE,
    UPDATE_BY_PROVINCE,
    UPDATE_BY_TOWN,
    UPDATE_LOADING,

    UPDATE_VIEW
}